# Applied AI Systems - Professional Pre-commit Configuration
# Government contractor grade code quality standards

repos:
  # Code formatting and linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: detect-private-key
      - id: mixed-line-ending
      - id: fix-byte-order-marker

  # TypeScript/JavaScript linting and formatting
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint --fix
        language: system
        files: \.(js|jsx|ts|tsx)$
        stages: [pre-commit]

      - id: prettier
        name: prettier
        entry: npx prettier --write
        language: system
        files: \.(js|jsx|ts|tsx|json|css|md|yaml|yml)$
        stages: [pre-commit]

      # Temporarily disabled - Next.js type checking needs build context
      # - id: type-check
      #   name: TypeScript type check
      #   entry: npm run type-check
      #   language: system
      #   files: \.(ts|tsx)$
      #   stages: [pre-commit]
      #   pass_filenames: false

  # Security scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package-lock.json

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: ['--fix']
        files: \.md$

  # Git commit message formatting
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  # License header enforcement
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: insert-license
        files: \.(js|jsx|ts|tsx)$
        args:
          - --license-filepath
          - LICENSE-HEADER.txt
          - --comment-style
          - //
